2020-07-10 17:41:24.738 [error] <0.4383.0> CRASH REPORT Process <0.4383.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 17:41:24.746 [error] <0.4383.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.4376.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 17:41:27.479 [error] <0.4396.0> CRASH REPORT Process <0.4396.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 17:41:27.479 [error] <0.4396.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.4376.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 17:41:33.959 [error] <0.4410.0> CRASH REPORT Process <0.4410.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 17:41:33.959 [error] <0.4410.0> Cowboy stream 4 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.4376.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:12:36.440 [error] <0.4671.0> CRASH REPORT Process <0.4671.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:12:36.440 [error] <0.4671.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.4612.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:13:37.579 [error] <0.4805.0> CRASH REPORT Process <0.4805.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.CustomerLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/customer_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.CustomerLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:13:37.580 [error] <0.4805.0> Cowboy stream 21 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.4533.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.CustomerLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/customer_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.CustomerLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:22:29.497 [error] <0.5431.0> CRASH REPORT Process <0.5431.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:22:29.498 [error] <0.5431.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.5430.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:13.771 [error] <0.6083.0> CRASH REPORT Process <0.6083.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:13.772 [error] <0.6085.0> CRASH REPORT Process <0.6085.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:13.964 [error] <0.6142.0> CRASH REPORT Process <0.6142.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:13.968 [error] <0.6142.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6141.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:29.265 [error] <0.6192.0> CRASH REPORT Process <0.6192.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:29.265 [error] <0.6192.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6080.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:29.297 [error] <0.6186.0> CRASH REPORT Process <0.6186.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:29.299 [error] <0.6186.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6081.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:29.427 [error] <0.6237.0> CRASH REPORT Process <0.6237.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:29.436 [error] <0.6237.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6080.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.141 [error] <0.6282.0> CRASH REPORT Process <0.6282.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.161 [error] <0.6273.0> CRASH REPORT Process <0.6273.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.162 [error] <0.6273.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6272.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.329 [error] <0.6332.0> CRASH REPORT Process <0.6332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.330 [error] <0.6332.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6331.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:35.072 [error] <0.6402.0> CRASH REPORT Process <0.6402.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:35.074 [error] <0.6402.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6272.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:39:09.566 [error] <0.6433.0> CRASH REPORT Process <0.6433.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:39:09.573 [error] <0.6433.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6432.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:14.241 [error] <0.6466.0> CRASH REPORT Process <0.6466.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:14.242 [error] <0.6466.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6458.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:14.361 [error] <0.6523.0> CRASH REPORT Process <0.6523.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:14.364 [error] <0.6523.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6522.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:34.306 [error] <0.6566.0> CRASH REPORT Process <0.6566.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:34.306 [error] <0.6565.0> CRASH REPORT Process <0.6565.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:34.445 [error] <0.6623.0> CRASH REPORT Process <0.6623.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:34.445 [error] <0.6623.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6458.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:37.102 [error] <0.6656.0> CRASH REPORT Process <0.6656.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:37.104 [error] <0.6656.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6564.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:41.468 [error] <0.6668.0> CRASH REPORT Process <0.6668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:41.469 [error] <0.6668.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6564.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:03:16.151 [error] <0.7564.0> CRASH REPORT Process <0.7564.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.Index.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/index.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:03:16.152 [error] <0.7564.0> Cowboy stream 6 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.7409.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.Index.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/index.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:04:24.243 [error] <0.7583.0> CRASH REPORT Process <0.7583.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.Index.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live/index.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:04:24.243 [error] <0.7583.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.7582.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.Index.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live/index.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:04:32.241 [error] <0.7671.0> CRASH REPORT Process <0.7671.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.Index.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live/index.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:04:32.242 [error] <0.7671.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.7670.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.Index.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live/index.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:05:51.016 [error] <0.7863.0> CRASH REPORT Process <0.7863.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:05:51.018 [error] <0.7863.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.7862.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:07:55.157 [error] <0.7948.0> CRASH REPORT Process <0.7948.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:07:55.159 [error] <0.7948.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.7947.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:08:07.433 [error] <0.8017.0> CRASH REPORT Process <0.8017.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:08:07.434 [error] <0.8017.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8016.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:08:56.975 [error] <0.8142.0> CRASH REPORT Process <0.8142.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:08:56.976 [error] <0.8142.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8140.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:09:03.636 [error] <0.8218.0> CRASH REPORT Process <0.8218.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityApp',reason => nil},[{'Elixir.FidelityApp',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:09:03.636 [error] <0.8218.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8217.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityApp',reason => nil},[{'Elixir.FidelityApp',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:09:10.967 [error] <0.8299.0> CRASH REPORT Process <0.8299.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:09:10.967 [error] <0.8299.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8298.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:09:38.692 [error] <0.8382.0> CRASH REPORT Process <0.8382.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:09:38.693 [error] <0.8382.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8381.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:10:38.611 [error] <0.8462.0> CRASH REPORT Process <0.8462.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:10:38.613 [error] <0.8462.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8461.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb',reason => nil},[{'Elixir.FidelityAppWeb',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:10:55.584 [error] <0.8539.0> CRASH REPORT Process <0.8539.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb.AdminuserView',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => ...,...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:10:55.585 [error] <0.8539.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8537.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb.AdminuserView',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => ...,...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:11:04.249 [error] <0.8614.0> CRASH REPORT Process <0.8614.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb.AdminuserView',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => ...,...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:11:04.249 [error] <0.8614.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8613.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.FidelityAppWeb.AdminuserView',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminuserLive.Index',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => ...,...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:11:25.355 [error] <0.8770.0> CRASH REPORT Process <0.8770.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:11:25.355 [error] <0.8770.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8769.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminu...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:12:28.634 [error] <0.8938.0> CRASH REPORT Process <0.8938.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Show','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:12:28.634 [error] <0.8938.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8880.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Show','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:12:32.286 [error] <0.8965.0> CRASH REPORT Process <0.8965.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:12:32.286 [error] <0.8965.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8880.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:16:02.848 [error] <0.9433.0> CRASH REPORT Process <0.9433.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:16:02.849 [error] <0.9433.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9353.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:16:59.405 [error] <0.9482.0> CRASH REPORT Process <0.9482.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:16:59.406 [error] <0.9482.0> Cowboy stream 4 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9377.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:17:17.557 [error] <0.9494.0> CRASH REPORT Process <0.9494.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:17:17.557 [error] <0.9494.0> Cowboy stream 6 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9377.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:17:59.472 [error] <0.9622.0> CRASH REPORT Process <0.9622.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:17:59.472 [error] <0.9622.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9567.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:19:56.913 [error] <0.9793.0> CRASH REPORT Process <0.9793.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:19:56.913 [error] <0.9793.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9792.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:20:03.312 [error] <0.9873.0> CRASH REPORT Process <0.9873.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:20:03.313 [error] <0.9873.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9872.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:23:00.998 [error] <0.10008.0> CRASH REPORT Process <0.10008.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:23:00.999 [error] <0.10008.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9970.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:26:36.280 [error] <0.10283.0> CRASH REPORT Process <0.10283.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:26:36.286 [error] <0.10283.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10282.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:27:13.380 [error] <0.10385.0> CRASH REPORT Process <0.10385.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:27:13.381 [error] <0.10385.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10282.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:29:10.865 [error] <0.10500.0> CRASH REPORT Process <0.10500.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:29:14.420 [error] <0.10574.0> CRASH REPORT Process <0.10574.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:29:14.420 [error] <0.10574.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10499.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:29:47.947 [error] <0.10597.0> CRASH REPORT Process <0.10597.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:29:47.948 [error] <0.10597.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10596.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:29:53.524 [error] <0.10673.0> CRASH REPORT Process <0.10673.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:29:53.526 [error] <0.10673.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10596.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:30:17.687 [error] <0.10771.0> CRASH REPORT Process <0.10771.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:30:17.689 [error] <0.10771.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10689.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:30:55.733 [error] <0.10791.0> CRASH REPORT Process <0.10791.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:30:55.734 [error] <0.10791.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10789.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:31:01.470 [error] <0.10866.0> CRASH REPORT Process <0.10866.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:31:01.471 [error] <0.10866.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10789.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:32:08.590 [error] <0.10903.0> CRASH REPORT Process <0.10903.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:32:08.593 [error] <0.10903.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10902.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:34:22.190 [error] <0.10941.0> CRASH REPORT Process <0.10941.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:34:22.190 [error] <0.10941.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10920.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:36:32.493 [error] <0.10969.0> CRASH REPORT Process <0.10969.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:36:32.493 [error] <0.10969.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10966.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:36:51.423 [error] <0.11044.0> CRASH REPORT Process <0.11044.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:36:51.424 [error] <0.11044.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10966.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:37:01.003 [error] <0.11077.0> CRASH REPORT Process <0.11077.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:37:01.004 [error] <0.11077.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.11065.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:16.468 [error] <0.11205.0> CRASH REPORT Process <0.11205.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:16.469 [error] <0.11205.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.11098.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:18.265 [error] <0.11219.0> CRASH REPORT Process <0.11219.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action FidelityAppWeb.AdminuserLive.Edit for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Show, id, params \\\\ [])\n    live_path(conn_or_endpoint, Fideli...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:18.265 [error] <0.11219.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.11098.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action FidelityAppWeb.AdminuserLive.Edit for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Show, id, params \\\\ [])\n    live_path(conn_or_endpoint, Fideli...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:20.319 [error] <0.11230.0> CRASH REPORT Process <0.11230.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action FidelityAppWeb.AdminuserLive.Edit for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Show, id, params \\\\ [])\n    live_path(conn_or_endpoint, Fideli...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:20.320 [error] <0.11230.0> Cowboy stream 6 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.11098.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action FidelityAppWeb.AdminuserLive.Edit for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Show, id, params \\\\ [])\n    live_path(conn_or_endpoint, Fideli...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:55.193 [error] <0.11299.0> CRASH REPORT Process <0.11299.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:55.196 [error] <0.11299.0> Cowboy stream 12 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.11098.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:39:33.565 [error] <0.11468.0> CRASH REPORT Process <0.11468.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:39:33.565 [error] <0.11468.0> Cowboy stream 4 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.11359.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:40:33.955 [info] <0.43.0> Application lager started on node nonode@nohost
2020-07-10 19:40:33.971 [info] <0.43.0> Application gen_stage started on node nonode@nohost
2020-07-10 19:40:33.983 [info] <0.43.0> Application broadway started on node nonode@nohost
2020-07-10 19:40:34.122 [info] <0.43.0> Application jsx started on node nonode@nohost
2020-07-10 19:40:34.129 [info] <0.43.0> Application recon started on node nonode@nohost
2020-07-10 19:40:34.166 [info] <0.43.0> Application credentials_obfuscation started on node nonode@nohost
2020-07-10 19:40:34.167 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2020-07-10 19:40:34.185 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2020-07-10 19:40:34.195 [info] <0.43.0> Application amqp started on node nonode@nohost
2020-07-10 19:40:34.195 [info] <0.43.0> Application broadway_rabbitmq started on node nonode@nohost
2020-07-10 19:40:34.273 [info] <0.43.0> Application fidelity_rule_engine started on node nonode@nohost
2020-07-10 19:40:34.294 [info] <0.43.0> Application absinthe started on node nonode@nohost
2020-07-10 19:40:34.310 [info] <0.43.0> Application poison started on node nonode@nohost
2020-07-10 19:40:34.318 [info] <0.43.0> Application argon2_elixir started on node nonode@nohost
2020-07-10 19:40:34.333 [info] <0.43.0> Application absinthe_ecto started on node nonode@nohost
2020-07-10 19:40:34.342 [info] <0.43.0> Application absinthe_error_payload started on node nonode@nohost
2020-07-10 19:40:34.344 [info] <0.43.0> Application absinthe_plug started on node nonode@nohost
2020-07-10 19:40:34.763 [info] <0.43.0> Application jose started on node nonode@nohost
2020-07-10 19:40:34.763 [info] <0.43.0> Application guardian started on node nonode@nohost
2020-07-10 19:40:34.787 [info] <0.43.0> Application guardian_db started on node nonode@nohost
2020-07-10 19:40:34.800 [info] <0.43.0> Application basic_auth started on node nonode@nohost
2020-07-10 19:40:34.820 [info] <0.43.0> Application pow started on node nonode@nohost
2020-07-10 19:40:35.160 [info] <0.43.0> Application mnesia started on node nonode@nohost
2020-07-10 19:40:35.173 [info] <0.43.0> Application gqlgateway started on node nonode@nohost
2020-07-10 19:40:39.560 [error] <0.1074.0> CRASH REPORT Process <0.1074.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:40:39.572 [error] <0.1074.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1072.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:43:43.446 [error] <0.1238.0> CRASH REPORT Process <0.1238.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:43:43.446 [error] <0.1238.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1237.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:43:59.535 [error] <0.1315.0> CRASH REPORT Process <0.1315.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:43:59.536 [error] <0.1315.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1237.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:45:08.708 [error] <0.1329.0> CRASH REPORT Process <0.1329.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:45:08.708 [error] <0.1329.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1328.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:48:49.415 [error] <0.1485.0> CRASH REPORT Process <0.1485.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:48:49.416 [error] <0.1485.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1484.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action Adminuser.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Adminuser...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:50:01.477 [error] <0.1606.0> CRASH REPORT Process <0.1606.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:50:01.478 [error] <0.1606.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1594.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:50:16.634 [error] <0.1625.0> CRASH REPORT Process <0.1625.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:50:16.634 [error] <0.1625.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1502.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:51:49.092 [error] <0.1782.0> CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:51:49.100 [error] <0.1782.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1781.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:52:25.383 [error] <0.1875.0> CRASH REPORT Process <0.1875.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:52:25.383 [error] <0.1875.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1874.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:52:35.379 [error] <0.1953.0> CRASH REPORT Process <0.1953.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:52:35.379 [error] <0.1953.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1951.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:57:10.122 [error] <0.2039.0> CRASH REPORT Process <0.2039.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:57:10.123 [error] <0.2039.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2037.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:57:32.712 [error] <0.2125.0> CRASH REPORT Process <0.2125.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:57:32.713 [error] <0.2125.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2124.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:06:18.998 [error] <0.2455.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2454.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => change_user,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',change_user,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => 'Elixir.NaiveDateTime',...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:15:01.236 [error] <0.2675.0> CRASH REPORT Process <0.2675.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"giving a struct to Ecto.Repo.update/2 is not supported. Ecto is unable to properly track changes when a struct is given, an Ecto.Changeset must be given instead">>},[{'Elixir.Ecto.Repo.Schema',update,4,[{file,"lib/ecto/repo/schema.ex"},{line,292}]},{'Elixir.FidelityAppWeb.AdminuserLive.Edit',mount,3,[{file,"lib/fidelity_app_web/live/adminuser_live/edit.ex"},{line,16}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:15:01.236 [error] <0.2675.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2673.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"giving a struct to Ecto.Repo.update/2 is not supported. Ecto is unable to properly track changes when a struct is given, an Ecto.Changeset must be given instead">>},[{'Elixir.Ecto.Repo.Schema',update,4,[{file,"lib/ecto/repo/schema.ex"},{line,292}]},{'Elixir.FidelityAppWeb.AdminuserLive.Edit',mount,3,[{file,"lib/fidelity_app_web/live/adminuser_live/edit.ex"},{line,16}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:17:25.576 [error] <0.2765.0> CRASH REPORT Process <0.2765.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:17:25.588 [error] <0.2765.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2764.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:17:57.124 [error] <0.2850.0> CRASH REPORT Process <0.2850.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:17:57.125 [error] <0.2850.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2849.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:18:44.348 [error] <0.2930.0> CRASH REPORT Process <0.2930.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:18:44.348 [error] <0.2930.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2928.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:19:56.440 [error] <0.3092.0> CRASH REPORT Process <0.3092.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:19:56.440 [error] <0.3092.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.3012.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:20:48.675 [error] <0.3238.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:25 gen_server <0.3238.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 25
2020-07-10 20:20:48.718 [error] <0.3238.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3238.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>})
2020-07-10 20:20:48.720 [error] <0.480.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.480.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3238.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:20:49.743 [error] <0.3303.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:25 gen_server <0.3303.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 25
2020-07-10 20:20:49.748 [error] <0.3303.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3303.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>})
2020-07-10 20:20:49.749 [error] <0.477.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3303.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:21:27.113 [error] <0.3369.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:26 gen_server <0.3369.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 26
2020-07-10 20:21:27.126 [error] <0.3369.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3369.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>})
2020-07-10 20:21:27.127 [error] <0.481.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3369.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:21:28.142 [error] <0.3433.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:26 gen_server <0.3433.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 26
2020-07-10 20:21:28.145 [error] <0.3433.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3433.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>})
2020-07-10 20:21:28.145 [error] <0.475.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.475.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3433.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:22:30.680 [error] <0.3520.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:27 gen_server <0.3520.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 27
2020-07-10 20:22:30.691 [error] <0.3520.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3520.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"customer">>})
2020-07-10 20:22:30.696 [error] <0.478.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3520.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"customer">>}) in context child_terminated
2020-07-10 20:22:31.710 [error] <0.3542.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:27 gen_server <0.3542.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 27
2020-07-10 20:22:31.712 [error] <0.3542.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3542.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"customer">>})
2020-07-10 20:22:31.713 [error] <0.478.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3542.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role_id">> => <<"customer">>}) in context child_terminated
2020-07-10 20:23:43.864 [error] <0.3633.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:27 gen_server <0.3633.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 27
2020-07-10 20:23:43.873 [error] <0.3633.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3633.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>})
2020-07-10 20:23:43.875 [error] <0.482.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.482.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3633.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:23:44.896 [error] <0.3669.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:27 gen_server <0.3669.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 27
2020-07-10 20:23:44.901 [error] <0.3669.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3669.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>})
2020-07-10 20:23:44.901 [error] <0.477.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3669.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:26:08.890 [error] <0.3931.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:34 gen_server <0.3931.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 34
2020-07-10 20:26:08.895 [error] <0.3931.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3931.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>})
2020-07-10 20:26:08.896 [error] <0.480.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.480.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3931.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:27:08.326 [error] <0.3984.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:36 gen_server <0.3984.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 36
2020-07-10 20:27:08.332 [error] <0.3984.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.3984.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>})
2020-07-10 20:27:08.333 [error] <0.477.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.3984.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"merchant">>}) in context child_terminated
2020-07-10 20:27:38.160 [error] <0.4071.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:36 gen_server <0.4071.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 36
2020-07-10 20:27:38.166 [error] <0.4071.0>@Elixir.FidelityApp.Accounts:set_role CRASH REPORT Process <0.4071.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"customer">>})
2020-07-10 20:27:38.166 [error] <0.475.0>@Elixir.FidelityApp.Accounts:set_role Supervisor {<0.475.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.4071.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':set_role(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"role">> => <<"customer">>}) in context child_terminated
2020-07-10 20:28:08.356 [error] <0.4252.0>@Elixir.Ecto.Repo.Schema:update:287 gen_server <0.4252.0> terminated with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"customer">>}, []) line 287
2020-07-10 20:28:08.370 [error] <0.4252.0>@Elixir.Ecto.Repo.Schema:update:287 CRASH REPORT Process <0.4252.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"customer">>}, []) line 287
2020-07-10 20:28:08.370 [error] <0.481.0>@Elixir.Ecto.Repo.Schema:update:287 Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.4252.0> exit with reason no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"customer">>}, []) line 287 in context child_terminated
2020-07-10 20:29:10.760 [error] <0.4324.0>@Elixir.Ecto.Repo.Schema:update:287 gen_server <0.4324.0> terminated with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"customer">>}, []) line 287
2020-07-10 20:29:10.762 [error] <0.4324.0>@Elixir.Ecto.Repo.Schema:update:287 CRASH REPORT Process <0.4324.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"customer">>}, []) line 287
2020-07-10 20:29:10.763 [error] <0.478.0>@Elixir.Ecto.Repo.Schema:update:287 Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.4324.0> exit with reason no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"customer">>}, []) line 287 in context child_terminated
2020-07-10 20:30:40.760 [error] <0.4725.0>@Elixir.Ecto.Repo.Schema:update:287 gen_server <0.4725.0> terminated with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"merchant">>}, []) line 287
2020-07-10 20:30:40.762 [error] <0.4725.0>@Elixir.Ecto.Repo.Schema:update:287 CRASH REPORT Process <0.4725.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"merchant">>}, []) line 287
2020-07-10 20:30:40.762 [error] <0.476.0>@Elixir.Ecto.Repo.Schema:update:287 Supervisor {<0.476.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.4725.0> exit with reason no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"merchant">>}, []) line 287 in context child_terminated
2020-07-10 20:34:15.114 [error] <0.4839.0>@Elixir.Ecto.Repo.Schema:update:287 gen_server <0.4839.0> terminated with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"merchant">>}, []) line 287
2020-07-10 20:34:15.121 [error] <0.4839.0>@Elixir.Ecto.Repo.Schema:update:287 CRASH REPORT Process <0.4839.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"merchant">>}, []) line 287
2020-07-10 20:34:15.122 [error] <0.475.0>@Elixir.Ecto.Repo.Schema:update:287 Supervisor {<0.475.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.4839.0> exit with reason no function clause matching 'Elixir.Ecto.Repo.Schema':update('Elixir.FidelityApp.Repo', 'Elixir.FidelityApp.Repo', #{<<"role">> => <<"merchant">>}, []) line 287 in context child_terminated
2020-07-10 20:38:00.837 [error] <0.5200.0>@Elixir.IO:inspect:414 gen_server <0.5200.0> terminated with reason: no function clause matching 'Elixir.IO':inspect({stop,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{changeset => #{'__struct__' => ...,...},...},...}}, label, <<"save">>) line 414
2020-07-10 20:38:00.839 [error] <0.5200.0>@Elixir.IO:inspect:414 CRASH REPORT Process <0.5200.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':inspect({stop,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{changeset => #{'__struct__' => ...,...},...},...}}, label, <<"save">>) line 414
2020-07-10 20:38:00.839 [error] <0.481.0>@Elixir.IO:inspect:414 Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.5200.0> exit with reason no function clause matching 'Elixir.IO':inspect({stop,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{changeset => #{'__struct__' => ...,...},...},...}}, label, <<"save">>) line 414 in context child_terminated
2020-07-10 20:38:35.348 [error] <0.5340.0> gen_server <0.5340.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_module: FidelityAppWeb.Ad...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:38:35.353 [error] <0.5340.0> CRASH REPORT Process <0.5340.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_module: FidelityAppWeb.Ad...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:38:35.355 [error] <0.481.0> Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.5340.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_module: FidelityAppWeb.Ad...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304 in context child_terminated
2020-07-10 20:38:50.561 [error] <0.5419.0> gen_server <0.5419.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"merchant\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:38:50.565 [error] <0.5419.0> CRASH REPORT Process <0.5419.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"merchant\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:38:50.566 [error] <0.480.0> Supervisor {<0.480.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.5419.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"merchant\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304 in context child_terminated
2020-07-10 20:40:55.465 [error] <0.5563.0> gen_server <0.5563.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"customer\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:40:55.466 [error] <0.5563.0> CRASH REPORT Process <0.5563.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"customer\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:40:55.466 [error] <0.479.0> Supervisor {<0.479.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.5563.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"customer\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304 in context child_terminated
2020-07-10 20:42:44.766 [error] <0.5640.0> gen_server <0.5640.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"merchant\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:42:44.768 [error] <0.5640.0> CRASH REPORT Process <0.5640.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"merchant\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:42:44.770 [error] <0.475.0> Supervisor {<0.475.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.5640.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"merchant\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_modul...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304 in context child_terminated
2020-07-10 20:44:14.928 [error] <0.5755.0> gen_server <0.5755.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for FidelityAppWeb.Router.Helpers.live_path/2 and action FidelityAppWeb.AdminuserLive.Show. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_...">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 374
2020-07-10 20:44:14.933 [error] <0.5755.0> CRASH REPORT Process <0.5755.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for FidelityAppWeb.Router.Helpers.live_path/2 and action FidelityAppWeb.AdminuserLive.Show. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_...">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 374
2020-07-10 20:44:14.934 [error] <0.479.0> Supervisor {<0.479.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.5755.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for FidelityAppWeb.Router.Helpers.live_path/2 and action FidelityAppWeb.AdminuserLive.Show. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_...">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 374 in context child_terminated
2020-07-10 20:45:38.461 [error] <0.5942.0> gen_server <0.5942.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for FidelityAppWeb.Router.Helpers.live_path/2 and action FidelityAppWeb.AdminuserLive.Show. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_...">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 374
2020-07-10 20:45:38.463 [error] <0.5942.0> CRASH REPORT Process <0.5942.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for FidelityAppWeb.Router.Helpers.live_path/2 and action FidelityAppWeb.AdminuserLive.Show. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_...">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 374
2020-07-10 20:45:38.463 [error] <0.476.0> Supervisor {<0.476.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.5942.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for FidelityAppWeb.Router.Helpers.live_path/2 and action FidelityAppWeb.AdminuserLive.Show. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_...">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 374 in context child_terminated
2020-07-10 20:47:29.788 [error] <0.6128.0> gen_server <0.6128.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"admin\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_module: ...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:47:29.790 [error] <0.6128.0> CRASH REPORT Process <0.6128.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"admin\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_module: ...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304
2020-07-10 20:47:29.791 [error] <0.476.0> Supervisor {<0.476.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.6128.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from FidelityAppWeb.AdminuserLive.Edit.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: {:stop, #Phoenix.LiveView.Socket<assigns: %{changeset: #Ecto.Changeset<action: :update, changes: %{role: \"admin\"}, errors: [], data: #FidelityApp.Accounts.User<>, valid?: true>, flash: %{\"info\" => \"User updated successfully.\"}, live_action: nil, live_module: ...">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 304 in context child_terminated
2020-07-10 20:48:58.597 [error] <0.6395.0>@Elixir.Phoenix.LiveView.Channel:-view_handle_event/3-fun-0-:213 gen_server <0.6395.0> terminated with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':'-view_handle_event/3-fun-0-'/3 line 213
2020-07-10 20:48:58.604 [error] <0.6395.0>@Elixir.FidelityAppWeb.AdminuserLive.Index:handle_event CRASH REPORT Process <0.6395.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive.Index':handle_event(<<"delete_user">>, #{}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...})
2020-07-10 20:48:58.604 [error] <0.475.0>@Elixir.FidelityAppWeb.AdminuserLive.Index:handle_event Supervisor {<0.475.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.6395.0> exit with reason call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive.Index':handle_event(<<"delete_user">>, #{}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...}) in context child_terminated
2020-07-10 20:50:32.457 [error] <0.6400.0>@Elixir.Phoenix.LiveView.Channel:-view_handle_event/3-fun-0-:213 gen_server <0.6400.0> terminated with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':'-view_handle_event/3-fun-0-'/3 line 213
2020-07-10 20:50:32.462 [error] <0.6400.0>@Elixir.FidelityAppWeb.AdminuserLive.Index:handle_event CRASH REPORT Process <0.6400.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive.Index':handle_event(<<"delete_user">>, #{}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...})
2020-07-10 20:50:32.469 [error] <0.478.0>@Elixir.FidelityAppWeb.AdminuserLive.Index:handle_event Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.6400.0> exit with reason call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive.Index':handle_event(<<"delete_user">>, #{}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...}) in context child_terminated
