2020-07-11 12:10:35.264 [error] <0.8690.0> CRASH REPORT Process <0.8690.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:10:35.265 [error] <0.8690.0> Cowboy stream 7 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:24.274 [error] <0.8705.0> CRASH REPORT Process <0.8705.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:24.275 [error] <0.8705.0> Cowboy stream 9 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:38.260 [error] <0.8774.0> CRASH REPORT Process <0.8774.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:38.260 [error] <0.8774.0> Cowboy stream 15 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:30.191 [error] <0.8786.0> CRASH REPORT Process <0.8786.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:30.192 [error] <0.8786.0> Cowboy stream 17 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:47.417 [error] <0.8856.0> CRASH REPORT Process <0.8856.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:47.418 [error] <0.8856.0> Cowboy stream 23 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:25.341 [error] <0.1101.0> CRASH REPORT Process <0.1101.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:25.375 [error] <0.1101.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1099.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:27.395 [error] <0.1159.0> CRASH REPORT Process <0.1159.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:27.396 [error] <0.1159.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1157.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
