2020-07-08 23:58:18.688 [info] <0.43.0> Application absinthe_ecto started on node nonode@nohost
2020-07-08 23:58:18.699 [info] <0.43.0> Application absinthe_error_payload started on node nonode@nohost
2020-07-09 09:32:38.551 [error] <0.1169.0>@Elixir.FidelityAppWeb.AdminuserLive:handle_info CRASH REPORT Process <0.1169.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive':handle_info({'Elixir.FidelityApp.Accounts',[user,created],#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...})
2020-07-09 09:32:38.551 [error] <0.511.0>@Elixir.FidelityAppWeb.AdminuserLive:handle_info Supervisor {<0.511.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.1169.0> exit with reason call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive':handle_info({'Elixir.FidelityApp.Accounts',[user,created],#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...}) in context child_terminated
2020-07-10 18:43:14.256 [error] <0.6465.0> CRASH REPORT Process <0.6465.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:14.257 [error] <0.6465.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6464.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:34.311 [error] <0.6579.0> CRASH REPORT Process <0.6579.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:43:34.312 [error] <0.6579.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6459.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:19:37.895 [error] <0.9715.0> CRASH REPORT Process <0.9715.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:19:37.906 [error] <0.9715.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.9713.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:40:34.036 [info] <0.43.0> Application xmerl started on node nonode@nohost
2020-07-10 19:40:34.100 [info] <0.43.0> Application sasl started on node nonode@nohost
2020-07-10 19:40:41.807 [error] <0.1155.0> CRASH REPORT Process <0.1155.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:50:42.907 [error] <0.1710.0> CRASH REPORT Process <0.1710.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:50:42.907 [error] <0.1710.0> Cowboy stream 6 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1503.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Edit',reason => nil},[{'Elixir.FidelityAppWeb.AdminuserLive.Edit','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:14:27.278 [error] <0.2558.0> CRASH REPORT Process <0.2558.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"giving a struct to Ecto.Repo.update/2 is not supported. Ecto is unable to properly track changes when a struct is given, an Ecto.Changeset must be given instead">>},[{'Elixir.Ecto.Repo.Schema',update,4,[{file,"lib/ecto/repo/schema.ex"},{line,292}]},{'Elixir.FidelityAppWeb.AdminuserLive.Edit',mount,3,[{file,"lib/fidelity_app_web/live/adminuser_live/edit.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:19:50.979 [error] <0.3014.0> CRASH REPORT Process <0.3014.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:19:50.980 [error] <0.3014.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.3012.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => changeset_role,message => nil,module => 'Elixir.FidelityApp.Accounts.User',reason => nil},[{'Elixir.FidelityApp.Accounts.User',changeset_role,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.FidelityApp.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.FidelityApp.Accounts.User',confirmed_at => #{'__struct__' => ...,...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-14 23:15:09.099 [info] <0.43.0> Application absinthe started on node nonode@nohost
2020-07-14 23:15:09.125 [info] <0.43.0> Application poison started on node nonode@nohost
